### PR TITLE
Requre and verify recipe signatures from Normandy

### PR DESCRIPTION
**Pull request by mythmon**
Fixes bug 1258806

@brittanystoroz r?

### CODE REVIEW

**Comment by mythmon** [comment]
To verify this, you need to use the [signing branch of Normandy](https://github.com/mozilla/normandy/tree/signing). I recommend [normandy-compose](https://github.com/mozilla/normandy-compose) to glue everything together. It includes an Autograph server (which is where the actually signing happens).

**Comment by brittanystoroz** [comment]
lgtm, just needs a rebase to resolve conflicts

**Comment by mythmon** [comment]
Merged master into this branch to fix conflicts ^

**Comment by brittanystoroz** [comment]
r+

**Pull request merged**
