### PR TITLE
Use simple prefs, and provide default prefs

### PR DESCRIPTION
**Pull request by mythmon**
This should make the addon a lot easier to set up and test.

Unfortunately, this PR will probably conflict with #12, but I can deal with that once one of them merges.

r?

### CODE REVIEW

**Comment by brittanystoroz** [comment]
I think there are a couple of my commits in here from the stable sampling. Can you rebase this off master since those have been merged?

**Comment by brittanystoroz** [comment]
Otherwise r+

**Comment by mythmon** [comment]
Huh. That's weird, I thought I rebased this already. Oh well.

**Comment by mythmon** [comment]
Rebased. Waiting for CI.

**Comment by brittanystoroz** [comment]
r+

**Pull request merged**
